apiVersion: v1
kind: ServiceAccount
metadata:
  name: fitness-app-sa
  namespace: default
  annotations:
    # This Client ID tells Workload Identity which Azure Identity to assume
    # Replace the value below with the Client ID(managed identity)
    azure.workload.identity/client-id: "076a865d-0832-482b-b2a4-76048c874b94"
  labels:
    azure.workload.identity/use: "true"
